const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001';

export const upaService = {
  async getDashboard() {
    try {
      console.log('[upaService] Fetching dashboard from:', `${API_URL}/skl/pengajuan`);
      const response = await fetch(`${API_URL}/skl/pengajuan`, {
        method: 'GET',
        credentials: 'include',
        headers: {
          'Content-Type': 'application/json',
        },
      });

      if (!response.ok) {
        console.error('[upaService] Failed to fetch:', response.status);
        throw new Error('Failed to fetch pengajuan');
      }

      const allPengajuan = await response.json();

      // Filter: UPA sees STEP_KONVENSIONAL (perlu action) and COMPLETED (sudah selesai = finalisasi UPA)
      const pengajuanList = allPengajuan.filter((p: any) => {
        // Status normal yang ditangani UPA
        if (p.status === 'STEP_KONVENSIONAL' || // Perlu finalisasi
          p.status === 'COMPLETED') {         // Sudah difinalisasi = selesai untuk UPA
          return true;
        }

        // DITOLAK hanya muncul jika surat pernah sampai ke UPA
        // (pernah ada status STEP_KONVENSIONAL atau COMPLETED di riwayat)
        if (p.status === 'DITOLAK' && p.riwayat && p.riwayat.length > 0) {
          const pernahDiUPA = p.riwayat.some((r: any) =>
            r.statusBaru === 'STEP_KONVENSIONAL' || r.statusBaru === 'COMPLETED'
          );
          if (pernahDiUPA) return true;
        }

        return false;
      });

      console.log('[upaService] Dashboard data:', pengajuanList);

      // Calculate stats
      const perluTindakan = allPengajuan.filter((p: any) => p.status === 'STEP_KONVENSIONAL');

      return {
        pengajuan: pengajuanList,
        perluTindakan: perluTindakan.length,
      };
    } catch (error) {
      console.error('[upaService] Error fetching dashboard:', error);
      throw error;
    }
  },

  async getPengajuanDetail(id: string) {
    try {
      console.log('[upaService] Fetching detail for:', id);
      const response = await fetch(`${API_URL}/skl/pengajuan/${id}`, {
        method: 'GET',
        credentials: 'include',
        headers: {
          'Content-Type': 'application/json',
        },
      });

      if (!response.ok) {
        console.error('[upaService] Failed to fetch detail:', response.status);
        throw new Error('Failed to fetch pengajuan detail');
      }

      const data = await response.json();
      console.log('[upaService] Detail data:', data);
      return data;
    } catch (error) {
      console.error('[upaService] Error fetching detail:', error);
      throw error;
    }
  },

  async finalisasi(id: string, actorId: string, nomorSklResmi: string, catatan?: string, pdfFinalPath?: string) {
    try {
      console.log('[upaService] Finalisasi surat dengan nomor SKL resmi:', { id, actorId, nomorSklResmi, catatan, pdfFinalPath });

      // TODO: Generate PDF with sticky notes using backend service
      // Backend should:
      // 1. Generate PDF from surat template with data
      // 2. Add sticky notes overlay to PDF
      // 3. Upload to Minio
      // 4. Return pdfFinalPath
      // For now, we'll set a placeholder path that will be generated by backend

      const finalPdfPath = pdfFinalPath || `skl-final/${id}-${Date.now()}.pdf`;

      const response = await fetch(`${API_URL}/skl/pengajuan/${id}/status`, {
        method: 'PATCH',
        credentials: 'include',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          status: 'COMPLETED',
          actorId,
          nomorSkl: nomorSklResmi,
          pdfFinalPath: finalPdfPath,
          catatan: catatan || `Surat SKL dengan nomor ${nomorSklResmi} telah selesai. Silakan mengambil Surat Keterangan Lulus di Akademik dengan membawa pas foto 4x6 dan meminta cap basah`,
        }),
      });

      if (!response.ok) {
        const errorText = await response.text();
        console.error('[upaService] Failed to update status:', response.status, errorText);
        throw new Error('Failed to update status');
      }

      console.log('[upaService] Status updated successfully');
      return true;
    } catch (error) {
      console.error('[upaService] Error updating status:', error);
      return false;
    }
  },
};
